version: '3.9'

services:

  app:
    build:
      context: ./docker/node
    image: gabrieldarosa/node-t1
    container_name: node
    volumes:
      - ./app/:/usr/src/app
    ports:
      - 3000
    networks:
      - test
  
  gateway:
    build:
      context: ./docker/nginx
    image: gabrieldarosa/nginx-t1
    container_name: nginx-t1
    ports:
      - 80:80
    networks:
      - test
    
  gdb:
    build:
      context: ./docker/postgreSQL
    image: gabrieldarosa/postgre-t1
    container_name: postgre-t1
    volumes:
      - ./docker/postgreSQL/data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_postgres
    networks:
      - test

networks:
  test:
    driver: bridge