version: '3.9'

services:

  app:
    build:
      context: ./docker/node
    image: gabrieldarosa/node-t1
    container_name: node1
    entrypoint: dockerize -wait tcp://dbpostgres:5432 -wait tcp://dbredis:6379 -timeout 40s tail -f /dev/null ##./entrypoint.sh
    volumes:
      - .:/usr/src/app
    networks:
      - test
    depends_on:
      - dbpostgres
  
  gateway:
    build:
      context: ./docker/nginx
    image: gabrieldarosa/nginx-t1
    container_name: nginx1
    ports:
      - 80:80
    networks:
      - test
    
  dbpostgres:
    build:
      context: ./docker/postgreSQL
    image: gabrieldarosa/postgre-t1
    container_name: postgre1
    volumes:
      - ./docker/postgreSQL/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_postgres
    networks:
      - test

  dbredis:
    build:
      context: ./docker/redis
    image: gabrieldarosa/redis-t1
    container_name: redis1
    networks:
      - test

networks:
  test:
    driver: bridge